#
#  swiftlint.yml
#  Live Target SwiftLint Configuration
#
#  Copyright © 2025 BCEAssociates, Inc. All rights reserved.
#

name: SwiftLint

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.swift'

jobs:
  swiftlint:
    name: SwiftLint Analysis
    runs-on: macos-15
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint
      run: |
        swiftlint lint --reporter github-actions-logging